# Generated by Django 4.0.4 on 2022-08-06 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_stars', models.IntegerField()),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_last_name', models.CharField(max_length=50)),
                ('profile_date_birth', models.DateField()),
                ('profile_photo', models.ImageField(upload_to='profile_photos')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
